
CREATE DATABASE SHOP
USE DATABASE

CREATE TABLE SHOP (
    SHO_ID INT, 
    SHO_NOMBRE VARCHAR (50) NOT NULL,
    SHO_DIRECCION VARCHAR (100) NOT NULL,
)
ALTER TABLE SHOP(
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO)
)

CREATE TABLE PRODUCTOS (
    PRO_ID INT,
    PRO_NOMBRE VARCHAR(50) NOT NULL,
    PRO_PRECIO DECIMAL (10,2) NOT NULL,
)
ALTER TABLE PRODUCTOS(
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_ID) FOREING KEY (PRO_SHO_ID) REDERENCE SHOP
)
CREATE TABLE CATEGORIA (
    CAT_ID INT,
    CAT_NOMBRE VARCHAR(50) NOT NULL,
)

ALTER TABLE CATEGORIA (
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_ID) FOREING KEY (PRO_SHO_ID) REDERENCE SHOP
)


CREATE TABLE VENDEDOR(
    VEN_ID INT,
    VEN_NOMBRE VARCHAR(30) NOT NULL,
)

ALTER TABLE VENDEDOR(
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_ID) FOREING KEY (PRO_SHO_ID) REDERENCE SHOP,
    ADD CONSTRAINT PK_SHO_DIRECCION FOREING KEY        //a chequear :|//
)

CREATE TABLE INGRESOS(
    ING_ID INT,
    ING_CANTIDAD DECIMAL(10,2) NOT NULL,
    ING_ORIGIN VARCHAR(30) NOT NULL,
)
ALTER TABLE INGRESOS(
    ADD CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_ID) FOREING KEY (PRO_SHO_ID) REDERENCE SHOP

)

INSERT INTO SHOP (SHO_ID, SHO_NOMBRE, SHO_DIRECCION)
VALUES (1, 'ARIES', 'BOLIVAR'),
VALUES (2, 'MIA', 'PEHUAJO'),
VALUES (3, 'ENTRENOSOTROS', 'NECOCHEA')


INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_PRECIO)
VALUES (1, 'SAHUMERIO', '$100,00'),
VALUES (2, 'PORTASAHUMERIO', '$350,00'),
VALUES (3, 'VELA, $230,00'),
VALUES (4, 'ATRATASUEÑOS, $1500,00'),
VALUES (5, 'PULSERA, $600,00') 

INSERT INTO CATEGORIA (ID, NOMBRE)
VALUES (1, 'ACCESORIO')
VALUES (2, 'MANUALIDAD')
VALUES (3, 'INCIENSO')

INSERT INTO VENDEDOR (ID, NOMBRE)
VALUES (1, 'FEDERICO')+
VALUES (2, 'BRUNO')
VALUES (3, 'ROCIO')
VALUES (4, 'MARIA')
VALUES (5, 'ERIKA')




